config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root to: 'questions#index'

  concern :votable do
    member do
      post :like
      post :dislike
      delete :unvote
    end
  end
  resources :comments, only: :create

  resources :attachments, shallow: true

  resources :user_mails, shallow: true

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        post :choose_best
      end
    end
  end

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users
      end
      resources :questions
      resources :answers
    end
  end

  get '/search', to: 'search#index', format: :json
  post '/search', to: 'search#index', format: :json
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, dependent: :destroy, as: :attachable
  has_many :user_mails

  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments

  after_update :subscribed_notification

  def subscribed_notification
    SubscribedQuestionJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: :show
  # authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner
    @question.save
    respond_with @question
  end

  def show
    respond_with @question
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: %i[new update create destroy]
  before_action :set_question, only: %i[show update destroy subscribe_to_question unsubscribe_from_question]

  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:notice] = 'Your question create'
      @user_mail = @question.user_mails.new
      @user_mail.user = current_user
      @user_mail.save
      redirect_to @question
    else
      render :new
    end
  end

  def show
    @subscribed = true if UserMail.find_by(user: current_user, question: @question)
    @answer = @question.answers.build
    @answers = @question.answers
    gon.question_id = @question.id
    if params[:answer]
      @answer.attachments.build if params[:answer][:attachments_attributes]
    end
  end

  def destroy
    respond_with(@question.destroy)

  end

  def update
    @question.update(question_params)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/questions',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, :user_id, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_attachment_fields.html.haml
.nested-fields
  .field
    = f.label :file
    %br
    = f.file_field :file
  = link_to_remove_association "remove field", f, name: 'add file'

app/views/questions/_form.html.haml
= nested_form_for @question, remote: true do |f|
  - if @question.errors.any?
    %h2
      = pluralize(@question.errors.count, "error")
      prohibited this train from being saved:
    %ul
      - @question.errors.full_messages.each do |message|
        %li= message

  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :body
    = f.text_field :body

  %p
    Attachments:
    = render 'attachments/form', f: f

  = f.submit "#{ @question.new_record? ? 'Create question' : 'Update question' }", class: 'submit_question_form'

app/views/questions/_question.html.haml
%h1= question.title
%br
= question.body
%br
  %p
    Attachments:
    %ul
      - question.attachments.each do |a|
        %li
          = link_to a.file.identifier, a.file.url
          = link_to 'Delete attachment', attachment_path(a), method: :delete, remote: true

    %div.question_comment_form
      = render 'comments/form', commentable_id: question.id, commentable_type: question.class

app/views/questions/_questions.html.haml
= link_to question.title, question
%br

app/views/questions/index.html.haml
%h1 Questions

%div.questions
  - @questions.each do |question|
    = render 'questions/questions', question: question

  - if can? :create, Question
    = link_to 'New question', new_question_path

app/views/questions/new.html.haml
%h1 New Question

= render 'form', hidden: false

app/views/questions/show.html.haml
%div.question
  %div.edit_question_form
    = render 'form'

  %div.question_data
    = render @question
  %div.question_errors
  %div.votes
    = @question.sum_of_votes

  %div.question_links
    - if @subscribed
      = link_to 'unsubscribe this question', user_mail_path(id: @question), method: :delete
    - else
      = link_to 'subscribe to this question', user_mails_path(id: @question), method: :post
    - if can? :update, @question
      = link_to 'Edit question', '', class: 'edit_question_link'
    - if can? :destroy, @question
      = link_to 'Delete question', question_path, method: :delete, remote: true
    - if can? :like, @question
      = link_to 'Vote for question', like_question_path(@question), method: :post, remote: true, class: 'vote_for_question'
    - if can? :dislike, @question
      = link_to 'Vote against question', dislike_question_path(@question), method: :post, remote: true, class: 'vote_against_question'
    - if can? :unvote, @question
      = link_to 'Delete my vote', unvote_question_path(@question), method: :delete, remote: true, class: 'unvote'


%br

%div.question_comments
  = render @question.comments

= render 'answers/form', answer: @answer

%div.answers
  = render 'answers/answers', answer: @question.answers

app/views/questions/update.js.erb
<% if @question.errors.any? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.errors').html("<%= j message %>");
  <% end %>
<% else %>
  $('.errors').html('');
$('.question_data').html('<%= j render 'question', question: @question %>');
  $('a.edit_question_link').click(function(e){
    e.preventDefault();
    Turbolinks.clearCache();

    var form = $('.edit_question_form');
    var question = $('.question_data');

    form.show();
    question.hide();
  })
<% end %>