config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root to: 'questions#index'

  concern :votable do
    member do
      post :like
      post :dislike
      delete :unvote
    end
  end
  resources :comments, only: :create

  resources :attachments, shallow: true

  resources :user_mails, shallow: true

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        post :choose_best
      end
    end
  end

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :users
      end
      resources :questions
      resources :answers
    end
  end

  get '/search', to: 'search#index', format: :json
  post '/search', to: 'search#index', format: :json
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  has_many :attachments, as: :attachable

  belongs_to :question
  belongs_to :user

  after_create :send_notice

  accepts_nested_attributes_for :attachments

  validates :body, presence: true

  scope :best, -> { order('best_answer desc') }

  def make_best
    previous_best = question.answers.where(best_answer: true).first
    if previous_best
      previous_best.best_answer = false
      previous_best.save
    end
    self.best_answer = true
    save
    question.answers
  end

  private

  def send_notice
    NewAnswerJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [:create]
  before_action :set_question, only: :create
  before_action :set_answer, only: %i[destroy update choose_best]

  after_action :publish_answer, only: [:create]

  authorize_resource

  respond_to :js

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
    if params[:answer]
      @answer.attachments.build if params[:answer][:attachments_attributes]
    end
    gon.question_id = @answer.question.id
    respond_with(@answer)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    @answer.destroy
    flash[:notice] = 'Your answer was deleted'
    redirect_to @answer.question
  end

  def choose_best
    respond_with(@answer.make_best)
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :body, :user_id, attachments_attributes: [:file])
  end

  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def publish_answer
    return if @answer.errors.any?
    pp @answer
    ActionCable.server.broadcast "questions/#{@answer.question_id}/answers", @answer.as_json.merge({sum: @answer.sum_of_votes})
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [:index, :create]
  before_action :set_answer, only: :show

  # authorize_resource

  def index
    respond_with @question.answers
  end

  def create
    @answer = @question.answers.build(answers_params)
    @answer.user = current_resource_owner
    @answer.save
    respond_with @answer
  end

  def show
    respond_with @answer
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answers_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.haml
- if answer.persisted?
  - if answer.best_answer
    "Best answer"
  %br/
  = answer.body
  %div{:class => "answer_votes_#{"#{answer.id}"}"}
    = answer.sum_of_votes
  %br
  - if can? :update, answer
    = link_to 'Edit answer', '', class: 'edit_answer_link', data: { answer_id: answer.id, turbolinks: false }
    = render 'answers/edit', answer: answer
  - if can? :destroy, answer
    = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
  - if can? :like, answer
    = link_to 'Vote for answer', like_answer_path(answer), method: :post, remote: true, class: 'vote_for_answer', data: { id: answer.id }
  - if can? :dislike, answer
    = link_to 'Vote against answer', dislike_answer_path(answer), method: :post, remote: true, class: 'vote_against_answer', data: { id: answer.id }
  - if can? :unvote, answer
    = link_to 'Delete my vote', unvote_answer_path(answer), method: :delete, remote: true, class: 'unvote_answer', data: { id: answer.id }
  - if can? :choose_best, answer
    = link_to 'Make this answer best', choose_best_answer_path(answer), class: 'choose_best_link', remote: true, method: :post
- answer.attachments.each do |attachment|
  %br/
  = link_to attachment.file.identifier, attachment.file.url
  = link_to 'Delete attachment', attachment_path(attachment), method: :delete, remote: true
  %br/
  %br/

%div{:class => "answer_#{answer.id}_comments"}
  = render answer.comments

%div.answer_comment_form
  = render 'comments/form', commentable_id: answer.id, commentable_type: answer.class

app/views/answers/_answers.html.haml
%p.notice= notice

%h3 Answers
- @question.answers.best.each do |answer|
  = render 'answers/answer', answer: answer


= javascript_include_tag 'answers'

app/views/answers/_attachment_fields.html.haml
.nested-fields
  .field
    = f.label :file
    %br
    = f.file_field :file
  = link_to_remove_association "remove field", f

app/views/answers/_edit.html.haml
%div.errors

= form_for answer, url: answer_path(answer.id), html: { id: "edit_answer_#{answer.id}" }, remote: true do |f|

  = f.label :edit_answer_body
  = f.text_field :body

  %h3 Attachments
  #tasks
    = f.fields_for :attachments do |a|
      = render 'attachments/attachment_fields', f: a
    .links
      = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_fields'

  = f.submit "#{answer.new_record? ? 'Create answer' : 'Update answer'}", class: 'submit_edit_answer_form', data: { 'answer_id': "#{answer.id}" }

app/views/answers/_form.html.haml
%div.errors
= form_for [@question, answer], url: question_answers_path(@question.id), remote: true do |f|
  .field
    = f.label :body
    %br
    = f.text_field :body
  %h3 Attachments
  #tasks
    = f.fields_for :attachments do |a|
      = render 'attachments/attachment_fields', f: a
    .links
      = link_to_add_association 'add file', f, :attachments, name: 'add file'
  = f.submit 'Create answer', class: 'answer_create_link'

app/views/answers/choose_best.js.erb
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.errors').html("<%= j message %>");
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'answers' %>');
<% end %>

app/views/answers/create.js.erb
$('.answers').html('<%= j render 'answers' %>');
$('#answer_body').val('');

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.errors').html("<%= j message %>");
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'answers' %>');
  $('a.edit_answer_link').click(function(e){
    e.preventDefault();
    Turbolinks.clearCache();
    
    var answer_id = $(this).data('answerId');

    $(this).hide();
    $('form#edit_answer_' + answer_id).show();
  });
<% end %>